"use client";

import { useEffect, useRef, useState } from "react";
import { SessionProvider, signIn, signOut, useSession } from "next-auth/react";
import { CopilotChat } from "@copilotkit/react-ui";
import { CopilotKit, useCopilotReadable } from "@copilotkit/react-core";
import { Bot, FileText, FolderKanban, Moon, Radar, Sparkles, Sun, Upload, User } from "lucide-react";
import { KnowledgeGraph } from "@/components/KnowledgeGraph";
import { SettingsPanel, type ThemePreset } from "@/components/SettingsPanel";
import { demoProject, graphContext, type ResearchDocument, type ResearchProject } from "@/lib/mockData";

const models = ["openai/gpt-4o-mini", "google/gemini-2.0-flash-001", "meta-llama/llama-3.1-70b-instruct", "anthropic/claude-3.5-sonnet"];
type Finding = { title: string; url: string; domain: string; summary: string };

function IconButton({ title, onClick, children }: { title: string; onClick: () => void; children: React.ReactNode }) { return <button type="button" title={title} aria-label={title} onClick={onClick} className="grid h-10 w-10 place-items-center rounded-full border border-slate-200 bg-white transition hover:bg-slate-100 theme-toggle">{children}</button>; }
/* eslint-disable @next/next/no-img-element */
function Profile() { const { data } = useSession(); const [open, setOpen] = useState(false); const user = data?.user; return <div className="relative"><IconButton title="Perfil" onClick={() => setOpen(!open)}>{user?.image ? <img src={user.image} alt="" className="h-10 w-10 rounded-full object-cover" /> : <User size={18} />}</IconButton>{open && <div className="absolute right-0 top-12 z-50 w-64 rounded-xl border bg-white p-4 shadow-xl theme-toggle"><p className="font-bold">{user?.name ?? "Invitado"}</p><p className="mt-1 text-sm text-slate-500">{user?.email ?? "Inicia sesión para guardar tus preferencias."}</p><button onClick={() => user ? signOut() : signIn("google")} className="mt-4 text-sm font-bold text-orange-600">{user ? "Cerrar sesión" : "Continuar con Google"}</button></div>}</div>; }
function Header({ project, model, setModel, dark, setDark, theme, setTheme, back }: { project?: ResearchProject; model: string; setModel: (v: string) => void; dark: boolean; setDark: (v: boolean) => void; theme: ThemePreset; setTheme: (v: ThemePreset) => void; back?: () => void }) { return <header className="flex h-16 items-center border-b bg-white px-4 shadow-sm theme-toggle"><div className="flex flex-1 items-center gap-3"><span className="rounded-lg bg-orange-500 p-2 text-white"><Sparkles size={18} /></span><div><p className="text-xs font-bold uppercase tracking-widest text-orange-500">Nexus Intellect</p><p className="text-sm font-bold">{project?.name ?? "Proyectos"}</p></div>{back && <button onClick={back} className="text-xs font-bold text-blue-800">Proyectos</button>}</div><label className="hidden flex-1 items-center justify-center gap-2 text-sm font-semibold md:flex"><Bot size={16} /><select value={model} onChange={(e) => setModel(e.target.value)} className="bg-transparent">{models.map((m) => <option key={m}>{m}</option>)}</select></label><div className="flex flex-1 justify-end gap-2"><SettingsPanel theme={theme} setTheme={setTheme} model={model} setModel={setModel} /><IconButton title={dark ? "Cambiar a modo claro" : "Cambiar a modo oscuro"} onClick={() => setDark(!dark)}>{dark ? <Sun size={18} /> : <Moon size={18} />}</IconButton><Profile /></div></header>; }
function Projects({ open }: { open: () => void }) { return <main className="min-h-[calc(100vh-4rem)] bg-slate-50 p-8"><h1 className="mx-auto max-w-5xl text-3xl font-bold">Tus proyectos de investigación</h1><button onClick={open} className="mx-auto mt-8 block w-full max-w-xl rounded-2xl border bg-white p-6 text-left shadow-sm hover:shadow-md"><FolderKanban className="text-orange-500" /><h2 className="mt-5 text-xl font-bold">{demoProject.name}</h2><p className="mt-2 text-sm text-slate-600">{demoProject.purpose}</p><span className="mt-5 block text-sm font-bold text-orange-600">Abrir proyecto →</span></button></main>; }
function Workspace() { const [project, setProject] = useState(demoProject); const [selectedId, setSelectedId] = useState(project.documents[0].id); const [findings, setFindings] = useState<Finding[]>([]); const [notice, setNotice] = useState(""); const input = useRef<HTMLInputElement>(null); const selected = project.documents.find((d) => d.id === selectedId) ?? project.documents[0];
  useCopilotReadable({ description: "Corpus actual del proyecto Nexus Intellect y relaciones justificadas del grafo. Usa solamente estos datos al responder y distingue entre citas y afinidades temáticas.", value: graphContext(project) });
  async function explore() { setNotice("Buscando avances…"); const r = await fetch("/api/discover", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ project, selectedDocument: selected }) }); const b = await r.json(); if (!r.ok) { setNotice(b.error ?? "La búsqueda falló."); return; } setFindings(b.findings); setNotice(""); }
  async function addDoi(doi: string) { const r = await fetch("/api/ingest", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ doi, project }) }); const b = await r.json(); if (!r.ok) { setNotice(b.error ?? "No se pudo agregar."); return; } setProject((p) => ({ ...p, documents: [...p.documents, b.document], edges: [...p.edges, ...b.edges] })); setSelectedId(b.document.id); setFindings([]); setNotice("Documento agregado al grafo."); }
  function addLocalFile(file: File) { const id = `local-${Date.now()}`; const document: ResearchDocument = { id, title: file.name.replace(/\.[^.]+$/, ""), year: new Date().getFullYear(), authors: ["Documento local"], summary: `Archivo ${file.name} añadido localmente. Su contenido se indexará cuando se habilite la ingesta de archivos.`, affinity: 70, affinityReason: "Documento incorporado manualmente al corpus del proyecto.", entities: ["documento local"], color: "teal" }; setProject((p) => ({ ...p, documents: [...p.documents, document] })); setSelectedId(id); setNotice(`“${file.name}” se agregó al proyecto.`); }
  return <main className="min-h-[calc(100vh-4rem)] bg-slate-50 p-4"><div className="grid gap-4 xl:grid-cols-[270px_minmax(0,1fr)_340px]"><aside className="rounded-xl border bg-white p-4"><h2 className="font-bold">Documentos</h2><input ref={input} type="file" accept=".md,.pdf" className="hidden" onChange={(e) => { const f = e.target.files?.[0]; if (f) addLocalFile(f); e.currentTarget.value = ""; }} /><button onClick={() => input.current?.click()} className="mt-4 flex h-10 w-full items-center justify-center gap-2 rounded-lg border border-dashed text-sm font-semibold text-blue-800"><Upload size={16} />Subir archivo</button>{project.documents.map((d) => <button key={d.id} onClick={() => setSelectedId(d.id)} className={`mt-3 w-full rounded-lg border p-3 text-left ${d.id === selectedId ? "border-orange-400 bg-orange-50" : "border-slate-200"}`}><FileText size={16} /><p className="mt-1 text-sm font-bold">{d.title}</p><p className="text-xs text-slate-500">{d.affinity}% afinidad</p></button>)}</aside><section><div className="mb-3 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-orange-500">Grafo de conocimiento</p><h2 className="text-xl font-bold">Conexiones justificadas</h2></div><button onClick={explore} className="flex h-10 items-center gap-2 rounded-lg bg-orange-500 px-3 text-sm font-bold text-white"><Radar size={17} />Explorar Vanguardia</button></div><KnowledgeGraph documents={project.documents} edges={project.edges} selectedId={selectedId} onSelect={(d) => setSelectedId(d.id)} onSelectEdge={(edge) => setNotice(edge.label)} />{notice && <p className="mt-3 rounded-lg bg-orange-50 p-3 text-sm text-orange-800">{notice}</p>}</section><aside className="space-y-4"><section className="rounded-xl border bg-white p-4"><p className="text-xs font-bold uppercase tracking-widest text-orange-500">Documento activo</p><h2 className="mt-2 font-bold">{selected.title}</h2><p className="mt-2 text-sm text-slate-600">{selected.summary}</p>{findings.map((f) => <article key={f.url} className="mt-3 border-t pt-3"><p className="text-sm font-bold">{f.title}</p><p className="mt-1 text-xs text-slate-500">{f.domain}</p><p className="mt-1 text-xs">{f.summary}</p><button onClick={() => addDoi(f.url)} className="mt-2 text-xs font-bold text-orange-600">Agregar al proyecto →</button></article>)}</section><section className="overflow-hidden rounded-xl border bg-white"><CopilotChat labels={{ title: "Agente de investigación", initial: "Pregunta por una conexión del grafo." }} /></section></aside></div></main>; }
function App() { const [workspace, setWorkspace] = useState(false); const [model, setModel] = useState(models[0]); const [dark, setDark] = useState(false); const [theme, setTheme] = useState<ThemePreset>("vanguardia"); useEffect(() => { document.documentElement.classList.toggle("theme-dark", dark); document.documentElement.dataset.theme = theme; }, [dark, theme]); return <CopilotKit runtimeUrl={`/api/copilotkit?model=${model}`}><Header project={workspace ? demoProject : undefined} model={model} setModel={setModel} dark={dark} setDark={setDark} theme={theme} setTheme={setTheme} back={workspace ? () => setWorkspace(false) : undefined} />{workspace ? <Workspace /> : <Projects open={() => setWorkspace(true)} />}</CopilotKit>; }
export default function Home() { return <SessionProvider><App /></SessionProvider>; }
