"use client";

import { useEffect, useMemo, useState } from "react";
import { signIn, signOut, useSession } from "next-auth/react";
import { CopilotChat } from "@copilotkit/react-ui";
import { CopilotKit, useCopilotReadable } from "@copilotkit/react-core";
import { Bell, Bot, BookOpen, ChevronRight, CircleCheck, FileText, FolderOpen, GitBranch, Globe2, LogOut, Network, Plus, Radar, Search, Settings2, Sparkles, User, X } from "lucide-react";
import { DocumentEditor } from "@/components/DocumentEditor";
import { KnowledgeGraph } from "@/components/KnowledgeGraph";
import { SettingsPanel, type ThemePreset } from "@/components/SettingsPanel";
import { demoProject, graphContext, type ResearchDocument, type ResearchProject } from "@/lib/mockData";

const models = ["openai/gpt-4o-mini", "google/gemini-2.0-flash-001", "meta-llama/llama-3.1-70b-instruct", "anthropic/claude-3.5-sonnet"];
const projectStore = "nexus-project-enterprise-v1";
const editorStore = "nexus-editor-enterprise-v1";
type Finding = { title: string; url: string; domain: string; summary: string; publishedDate?: string };
type Notice = { message: string; error?: boolean } | null;

function ProfileMenu() {
  const { data } = useSession();
  const [open, setOpen] = useState(false);
  return <div className="relative"><button onClick={() => setOpen(!open)} className="grid h-9 w-9 place-items-center rounded-lg nx-btn-secondary" title="Cuenta">{data?.user?.image ? <img src={data.user.image} alt="" className="h-full w-full rounded-lg object-cover" /> : <User size={17} />}</button>{open && <div className="absolute right-0 top-11 z-50 w-64 rounded-xl nx-panel p-3 shadow-xl"><p className="text-sm font-bold">{data?.user?.name ?? "Investigador"}</p><p className="mt-1 text-xs nx-muted">{data?.user?.email ?? "Modo de investigación local"}</p><button className="mt-3 flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-sm hover:bg-black/5" onClick={() => data ? signOut() : signIn("google")}><LogOut size={15} />{data ? "Cerrar sesión" : "Conectar Google"}</button></div>}</div>;
}

function GraphWindow({ project, selectedId, onSelect, close }: { project: ResearchProject; selectedId: string; onSelect: (document: ResearchDocument) => void; close: () => void }) {
  const selected = project.documents.find((document) => document.id === selectedId) ?? project.documents[0];
  const [detail, setDetail] = useState("");
  return <div className="fixed inset-0 z-[200] bg-black/40 p-3 backdrop-blur-sm sm:p-6"><section role="dialog" aria-modal="true" aria-label="Ventana de grafo de conocimiento" className="nx-panel mx-auto flex h-full max-w-7xl flex-col overflow-hidden rounded-2xl shadow-2xl"><header className="flex items-center justify-between border-b px-5 py-4 nx-border"><div><p className="text-xs font-bold uppercase tracking-[.16em] nx-muted">Ventana contextual</p><h2 className="mt-1 text-lg font-bold">Grafo de evidencia y citación</h2></div><button onClick={close} className="grid h-9 w-9 place-items-center rounded-lg nx-btn-secondary" aria-label="Cerrar grafo"><X size={18} /></button></header><div className="grid min-h-0 flex-1 gap-0 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="min-h-[420px] p-4"><KnowledgeGraph documents={project.documents} edges={project.edges} selectedId={selectedId} onSelect={onSelect} onSelectEdge={(edge) => setDetail(edge.label)} /></div><aside className="overflow-auto border-l p-5 nx-border"><p className="text-xs font-bold uppercase tracking-[.16em] nx-muted">Nodo seleccionado</p><h3 className="mt-2 text-lg font-bold">{selected.title}</h3><p className="mt-3 text-sm leading-6 nx-muted">{selected.summary}</p><div className="mt-5 border-t pt-4 nx-border"><p className="text-xs font-bold uppercase tracking-[.16em] nx-muted">Lectura de la relación</p><p className="mt-2 text-sm leading-6">{detail || "Selecciona una arista para ver la justificación que conecta ambos documentos."}</p></div><button onClick={close} className="nx-btn-primary mt-6 inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold"><FileText size={15} />Volver al editor</button></aside></div></section></div>;
}

function SourceRow({ document, selected, onClick }: { document: ResearchDocument; selected: boolean; onClick: () => void }) {
  return <button onClick={onClick} className={`w-full rounded-lg border p-3 text-left transition ${selected ? "bg-black text-white" : "hover:bg-black/5"}`} style={{ borderColor: selected ? "var(--nx-accent)" : "var(--nx-line)" }}><div className="flex items-start gap-2"><FileText size={15} className={selected ? "mt-0.5 shrink-0" : "mt-0.5 shrink-0 nx-muted"} /><div className="min-w-0"><p className="line-clamp-2 text-sm font-bold">{document.title}</p><p className={`mt-1 text-xs ${selected ? "text-white/65" : "nx-muted"}`}>{document.year} · {document.authors[0]}</p></div></div></button>;
}

function Workspace({ theme, setTheme, model, setModel }: { theme: ThemePreset; setTheme: (theme: ThemePreset) => void; model: string; setModel: (model: string) => void }) {
  const [project, setProject] = useState<ResearchProject>(demoProject);
  const [selectedId, setSelectedId] = useState(demoProject.documents[0].id);
  const [editorContent, setEditorContent] = useState("");
  const [query, setQuery] = useState("");
  const [source, setSource] = useState("");
  const [busy, setBusy] = useState<"ingest" | "radar" | null>(null);
  const [findings, setFindings] = useState<Finding[]>([]);
  const [graphOpen, setGraphOpen] = useState(false);
  const [notice, setNotice] = useState<Notice>(null);
  useEffect(() => { try { const saved = localStorage.getItem(projectStore); if (saved) { const next = JSON.parse(saved) as ResearchProject; if (next.documents?.length) { setProject(next); setSelectedId(next.documents[0].id); } } const draft = localStorage.getItem(editorStore); if (draft) setEditorContent(draft); } catch { /* A fresh workspace is always available. */ } }, []);
  useEffect(() => { localStorage.setItem(projectStore, JSON.stringify(project)); }, [project]);
  useCopilotReadable({ description: "Nexus workspace: corpus, graph citations, thematic links and active research goal. Answer with evidence from these sources, identify uncertainty, and suggest an explicit next action.", value: graphContext(project) });
  const selected = project.documents.find((document) => document.id === selectedId) ?? project.documents[0];
  const filtered = useMemo(() => project.documents.filter((document) => `${document.title} ${document.summary} ${document.entities.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [project.documents, query]);
  const citations = project.edges.filter((edge) => edge.kind === "citation").length;
  function report(message: string, error = false) { setNotice({ message, error }); window.setTimeout(() => setNotice(null), 4600); }
  async function ingest(value: string) {
    const sourceValue = value.trim(); if (!sourceValue || busy) return;
    setBusy("ingest"); report("Nexus está extrayendo metadatos, entidades y referencias…");
    try { const response = await fetch("/api/ingest", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source: sourceValue, project }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "No fue posible incorporar la fuente."); setProject((current) => ({ ...current, documents: [...current.documents, body.document], edges: [...current.edges, ...body.edges] })); setSelectedId(body.document.id); setSource(""); setFindings((items) => items.filter((item) => item.url !== sourceValue)); report(body.simulated ? "Fuente registrada; falta enriquecerla cuando las integraciones estén disponibles." : "Fuente enriquecida y conectada al grafo."); } catch (error) { report(error instanceof Error ? error.message : "La ingesta falló.", true); } finally { setBusy(null); }
  }
  async function radar() {
    setBusy("radar"); report("Contrastando el nodo activo con investigación reciente…");
    try { const response = await fetch("/api/discover", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ project, selectedDocument: selected }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "No fue posible consultar la vanguardia."); setFindings(body.findings); report(`${body.findings.length} señales nuevas para revisar.`); } catch (error) { report(error instanceof Error ? error.message : "La búsqueda falló.", true); } finally { setBusy(null); }
  }
  return <div className="nx-shell"><div className="sticky top-0 z-40 flex h-14 items-center gap-3 border-b px-4 nx-panel"><div className="flex min-w-0 flex-1 items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg nx-btn-primary"><Sparkles size={16} /></span><div className="min-w-0"><p className="truncate text-sm font-bold">Nexus Intellect</p><p className="text-[10px] font-bold uppercase tracking-[.16em] nx-muted">Research operating system</p></div></div><div className="hidden items-center gap-1 text-xs nx-muted md:flex"><CircleCheck size={14} style={{ color: "var(--nx-success)" }} />Corpus sincronizado <span className="mx-2">·</span><span>{project.documents.length} fuentes</span></div><SettingsPanel theme={theme} setTheme={setTheme} model={model} setModel={setModel} /><ProfileMenu /></div>
    <div className="mx-auto grid max-w-[1800px] gap-0 lg:grid-cols-[290px_minmax(0,1fr)_350px]"><aside className="border-r p-4 nx-panel nx-border"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] nx-muted">Biblioteca</p><h2 className="mt-1 font-bold">Corpus de investigación</h2></div><span className="rounded-md px-2 py-1 text-xs font-bold nx-soft">{project.documents.length}</span></div><div className="relative mt-4"><Search size={15} className="absolute left-3 top-3 nx-muted" /><input className="nx-input w-full rounded-lg py-2 pl-9 pr-3 text-sm" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por tema o entidad" /></div><div className="mt-3 max-h-[46vh] space-y-2 overflow-auto pr-1">{filtered.map((document) => <SourceRow key={document.id} document={document} selected={document.id === selectedId} onClick={() => setSelectedId(document.id)} />)}{filtered.length === 0 && <p className="rounded-lg p-3 text-sm nx-soft nx-muted">No hay fuentes que coincidan.</p>}</div><div className="mt-5 border-t pt-4 nx-border"><p className="text-xs font-bold uppercase tracking-[.16em] nx-muted">Ingesta verificable</p><p className="mt-1 text-xs leading-5 nx-muted">Agrega DOI o URL. Nexus extrae metadatos y solo crea aristas con explicación.</p><div className="mt-3 flex gap-2"><input className="nx-input min-w-0 flex-1 rounded-lg px-3 py-2 text-xs" value={source} onChange={(event) => setSource(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void ingest(source); }} placeholder="DOI o URL" /><button onClick={() => void ingest(source)} disabled={!source.trim() || Boolean(busy)} className="grid h-9 w-9 place-items-center rounded-lg nx-btn-primary" title="Incorporar fuente"><Plus size={17} /></button></div></div></aside>
      <main className="min-w-0 p-4 lg:border-r nx-border"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] nx-muted">Documento activo · espacio de autoría</p><p className="mt-1 text-sm nx-muted">El editor es la superficie de trabajo; el grafo vive en su propia ventana contextual.</p></div><button onClick={() => setGraphOpen(true)} className="nx-btn-secondary inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold"><Network size={16} />Abrir grafo <ChevronRight size={15} /></button></div><DocumentEditor title={selected.title} initialContent={editorContent} onChange={(content) => { setEditorContent(content); localStorage.setItem(editorStore, content); }} /></main>
      <aside className="space-y-4 p-4 nx-panel"><section className="rounded-xl border p-4 nx-border"><p className="text-xs font-bold uppercase tracking-[.16em] nx-muted">Contexto seleccionado</p><h2 className="mt-2 text-base font-bold">{selected.title}</h2><p className="mt-2 text-sm leading-6 nx-muted">{selected.summary}</p><div className="mt-4 flex flex-wrap gap-2">{selected.entities.slice(0, 5).map((entity) => <span key={entity} className="rounded-full px-2.5 py-1 text-xs font-semibold nx-soft">{entity}</span>)}</div><button onClick={() => setGraphOpen(true)} className="mt-4 inline-flex items-center gap-2 text-sm font-bold nx-accent"><GitBranch size={15} />Ver conexiones justificadas</button></section>
        <section className="rounded-xl border p-4 nx-border"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] nx-muted">Agente investigador</p><h2 className="mt-1 font-bold">Radar de vanguardia</h2></div><Radar size={18} /></div><p className="mt-2 text-sm leading-6 nx-muted">Busca trabajos recientes que extiendan, contradigan o cubran huecos del nodo activo.</p><button onClick={() => void radar()} disabled={Boolean(busy)} className="nx-btn-primary mt-4 flex w-full items-center justify-center gap-2 rounded-lg px-3 py-2 text-sm font-bold"><Globe2 size={15} />{busy === "radar" ? "Analizando evidencia…" : "Ejecutar exploración"}</button>{findings.length > 0 && <div className="mt-4 space-y-3 border-t pt-3 nx-border">{findings.slice(0, 3).map((finding) => <article key={finding.url} className="border-b pb-3 last:border-0 nx-border"><p className="text-sm font-bold leading-5">{finding.title}</p><p className="mt-1 text-xs nx-muted">{finding.domain}{finding.publishedDate ? ` · ${finding.publishedDate.slice(0, 10)}` : ""}</p><p className="mt-1 line-clamp-2 text-xs leading-5 nx-muted">{finding.summary}</p><button onClick={() => void ingest(finding.url)} className="mt-2 text-xs font-bold underline">Incorporar con evidencia</button></article>)}</div>}</section>
        <section className="rounded-xl border p-4 nx-border"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] nx-muted">Integridad del corpus</p><p className="mt-1 text-sm font-bold">{citations} citas · {project.edges.length - citations} afinidades</p></div><CircleCheck size={20} style={{ color: "var(--nx-success)" }} /></div><p className="mt-2 text-xs leading-5 nx-muted">Las citas y afinidades se muestran como relaciones distintas para evitar falsas atribuciones.</p></section>
        <section className="overflow-hidden rounded-xl border nx-border"><CopilotChat labels={{ title: "Nexus · copiloto de investigación", initial: "Pregunta por evidencia, contradicciones o un hueco del corpus." }} /></section></aside>
    </div>{graphOpen && <GraphWindow project={project} selectedId={selectedId} onSelect={(document) => setSelectedId(document.id)} close={() => setGraphOpen(false)} />}{notice && <div className={`fixed bottom-5 left-1/2 z-[300] w-[min(92vw,620px)] -translate-x-1/2 rounded-xl border px-4 py-3 text-sm font-semibold shadow-xl ${notice.error ? "bg-red-50 text-red-800" : "nx-panel"}`} style={notice.error ? { borderColor: "#fecaca" } : undefined}>{notice.message}</div>}
  </div>;
}

export default function Home() {
  const [model, setModel] = useState(models[0]);
  const [theme, setTheme] = useState<ThemePreset>("monochrome");
  useEffect(() => { document.documentElement.dataset.theme = theme; }, [theme]);
  return <CopilotKit runtimeUrl={`/api/copilotkit?model=${model}`}><Workspace theme={theme} setTheme={setTheme} model={model} setModel={setModel} /></CopilotKit>;
}
